### ISSUE TITLE
setVariable and setVariables method

### ISSUE THREAD

**Issue by oytunyuksel** [rodriados/mathr#4]
Hi,

This project is awesome. I tried such of projects like mathr, but i think mathr is the best.

I think, you must add some new methods for more usability. Such as setVariable($key, $value) and setVariables([$key1=>$value1,$key2=>$value2]).

Just a suggestion.

Good luck.

**Comment by rodriados** [comment]
Hello! Thank you for finding usefulness in my project.

I'll put your suggestion as an assignment. Although I've been working on other stuff lately, I'll implement it as well as optimizations these next days.
