### ISSUE TITLE
set function is not working

### ISSUE THREAD

**Issue by shishtpal** [rodriados/mathr#6]
Hi

following code is not working as described in README.md

```php
$mathr->set('triangle(b, h)', fn ($b, $h) => ($b * $h) / 2);
$result = $mathr->evaluate('triangle(5, 8)');
echo $result; // 20

```

please help, I tried different combinations but not working,

Thanks

**Comment by rodriados** [comment]
Hi,
Thank you for using my project, I hope you're liking it!
Could you please provide the code snippet that is not working for you? I could not replicate the error and all test cases are working fine. Could you validate whether you're using the project's last version?

**Comment by shishtpal** [comment]
Thank you @rodriados for your quick response & this awesome library, 
I installed latest version using composer but I didn't check if it's really updated, 
I didn't realize that Mathr-version3 requires PHP8 whereas I was using php7,
that's why It was not working before, 

Now I got it working after updating my PHP to version 8,
Thanks again, latest version is really great, specifically ability to use custom functions 😊👍

**Comment by rodriados** [comment]
Thank you for the kind words, @shishtpal!
I really hope the project has been useful for you.
You can get in touch with me anytime if you have further problems.

**Comment by shishtpal** [comment]
It is again you who has been kind enough to share your hard work @rodriados 
Yes It is useful to me, all thanks to you, 
Sure,
